import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,team,analytics }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
          <div className="container">
            <div className="header">
              <Link href="/">Home</Link>
              <Link href="/visitor">Visitor</Link>
            </div>
            <div className="inner">
              {team}
              {analytics}
            </div>
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
