import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ABeeZee } from "next/font/google";
import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const abeezee = ABeeZee({
  weight:'400',
  subsets: ["latin"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={abeezee.className}>
        {/* <div className="header">
          <Link href='/'>Home</Link>
          <div className="right">
            <Link href='/performance'>Performance</Link>
            <Link href='/reliability'>Reliability</Link>
            <Link href='/scalability'>Scalability</Link>
          </div>
        </div> */}
        {children}
      </body>
    </html>
  );
}
